create type public.content_status as enum ('draft','published','hidden');
create type public.destination_type as enum ('internal','external','drive','other');
create table public.profile (id uuid primary key default gen_random_uuid(), name text not null, headline text not null, bio text not null, email text not null, location text, photo_url text, resume_url text, updated_at timestamptz default now());
create table public.experiences (id uuid primary key default gen_random_uuid(), company text not null, position text not null, employment_type text, start_date date, end_date date, is_current boolean default false, description text, highlights jsonb default '[]', tags text[] default '{}', sort_order int default 0, featured boolean default false, status public.content_status default 'draft', created_at timestamptz default now(), updated_at timestamptz default now());
create table public.projects (id uuid primary key default gen_random_uuid(), title text not null, slug text unique not null, summary text not null, cover_url text, company text, category text, tags text[] default '{}', destination_type public.destination_type not null default 'internal', destination_url text, case_study jsonb, cta_label text default 'View project', sort_order int default 0, featured boolean default false, status public.content_status default 'draft', created_at timestamptz default now(), updated_at timestamptz default now(), constraint valid_external_url check (destination_type='internal' or destination_url ~ '^https://'));
alter table public.profile enable row level security; alter table public.experiences enable row level security; alter table public.projects enable row level security;
create policy "public reads only published experiences" on public.experiences for select using (status='published');
create policy "public reads only published projects" on public.projects for select using (status='published');
-- Add owner-only write policies after replacing OWNER_UUID with auth.uid() from your approved Google account.
