import Image from 'next/image';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {Nav,Footer} from '@/components/site-shell';
import {PageHero,ChapterEnd} from '@/components/portfolio-ui';
import {ProjectExplorer} from '@/components/project-explorer';
import {ContactComposer} from '@/components/contact-composer';
import {getExperiences,getProjects,getProfile} from '@/lib/store';
export const dynamic='force-dynamic';
const chapters={
 about:['01','ABOUT / 私について','A curious mind.','A builder at heart.','Product thinking, grounded in the people doing the work. Here is a little of the person behind the products.'],
 experience:['02','EXPERIENCE / 経験','Every team,','a new chapter.','A journey through logistics, enterprise platforms, analytics, and digital products—learning by building along the way.'],
 projects:['03','PROJECTS / 作品','From a question','to something useful.','Selected product work, system explorations, and ideas that connect people, data, and decisions.'],
 achievements:['04','MILESTONES / 挑戦','A little courage.','A lot of curiosity.','Competitions, communities, and learning experiences that pushed me to think beyond the obvious.'],
 contact:['05','CONTACT / 連絡','The next chapter','starts with hello.','Have a product challenge, an interesting idea, or a story to share? I would love to hear it.']
};
export default async function Page({params}:{params:Promise<{page:string}>}){
 const {page}=await params;if(!(page in chapters))notFound();
 const [number,kicker,title,accent,description]=chapters[page as keyof typeof chapters];
 const [experiences,projects,profile]=await Promise.all([getExperiences(),getProjects(),getProfile()]);
 return <><Nav/><main id="main-content"><PageHero {...{number,kicker,title,accent,description}}/><section id="chapter-content" className={'section chapter-content '+page}>
 {page==='about'&&<><div className="about-grid"><div className="about-portrait panel" data-tilt><span className="portrait-sun"/><Image src="/images/resanda-cutout.png" alt="Resanda Dezca Asyam" width={1024} height={1536}/><div className="portrait-label"><span>PRODUCT × DATA × AI</span><b>{profile.name}</b></div></div><div className="about-story"><p className="eyebrow">THE PERSON BEHIND THE PROCESS</p><h2>Making sense<br/>of <i>the messy middle.</i></h2><p>I am an Information Systems graduate from Universitas Indonesia, working across product management, business intelligence, and operational systems.</p><p>My experience spans logistics at Shopee, CRM and learning platforms at Unilever, cybersecurity products at Digiserve, and digital ecosystems at Bukalapak. Each role has taught me to connect business needs with the details that make a product usable.</p><p>I use AI throughout discovery, analysis, documentation, and validation. The goal stays human: give teams clearer information and fewer unnecessary steps.</p><div className="education-note"><b>Universitas Indonesia</b><span>Bachelor of Computer Science · Information Systems</span><small>2022–2026 · GPA 3.51</small></div></div></div><div className="section-heading"><div><p className="eyebrow">MY TOOLKIT</p><h2>Ways I <i>build.</i></h2></div></div><div className="skill-grid">{[['Product & delivery','Discovery, PRDs, business rules, acceptance criteria, UAT, Agile Scrum','Jira · Confluence · Trello · Notion'],['Data & insight','KPI design, dashboards, data validation, exploration, and reporting','SQL · PostgreSQL · Power BI · Python · Pandas'],['Design & technology','User flows, interface design, web development, and AI-assisted workflows','Figma · HTML · CSS · JavaScript · Laravel']].map(([t,d,tools],i)=><article className="panel" key={t} data-tilt><span className="note-index">0{i+1}</span><h3>{t}</h3><p>{d}</p><div className="tags"><span>{tools}</span></div></article>)}</div></>}
 {page==='experience'&&<div className="journey-layout"><aside className="journey-sidebar"><p className="eyebrow">FIELD NOTES</p><h2>Learning,<br/><i>in motion.</i></h2><p>From writing frontend code to defining cross-functional product systems.</p><div className="tags"><span>Product</span><span>Data</span><span>Technology</span></div></aside><div className="journey-timeline">{experiences.map((e,i)=><article className="journey-card" key={e.id}><span className="timeline-dot"/><small className="eyebrow">CHAPTER {String(i+1).padStart(2,'0')} · {e.period}</small><div className="role-heading"><span className="company-seal" aria-hidden="true">{e.company.slice(0,1)}</span><div><h3>{e.position}</h3><b>{e.company}</b></div></div><p>{e.description}</p>{e.highlights?.length&&<details><summary>Inside this role <span>+</span></summary><ul>{e.highlights.map(h=><li key={h}>{h}</li>)}</ul></details>}<div className="tags">{e.tags.map(t=><span key={t}>{t}</span>)}</div></article>)}</div></div>}
 {page==='projects'&&<ProjectExplorer projects={projects}/>}
 {page==='achievements'&&<><div className="award-grid">{[['2025','01','IDEAS Business Plan Competition','Universitas Gadjah Mada · International','Champion','Moelung: a digital platform connecting waste pickers, collection points, and traceable recycling flows.'],['2024','02','Young Entrepreneur Week','UIN Syarif Hidayatullah Jakarta · National','Champion','SafeIN: a smart card and app concept designed to help prevent the loss of personal valuables.'],['2024','03','Vivace Innovazione','Universitas Lambung Mangkurat · National','Runner-up','FOODY: an integrated food planning and waste prevention concept for the food and beverage industry.']].map(([year,n,title,org,rank,copy])=><article className="award-card panel" key={n} data-tilt><div className="award-top"><span>{year}</span><span className="award-medal" aria-hidden="true">✦</span></div><p className="award-rank">{rank}</p><h3>{title}</h3><small>{org}</small><p>{copy}</p><span className="award-number" aria-hidden="true">{n}</span></article>)}</div><div className="leadership"><div><p className="eyebrow">BEYOND THE DAY JOB</p><h2>Growing<br/><i>with others.</i></h2></div><div><article className="panel"><small>2024 / COMPFEST</small><h3>VPIC, Business-IT Case Competition</h3><p>Collaborated with XL Axiata on competition cases, supervised four divisions, and connected participants with judges, mentors, and sponsors.</p></article><article className="panel"><small>2023–2024 / BEM FASILKOM UI</small><h3>Head of Science & Student Development</h3><p>Organized business-plan and career-development activities, supporting student creativity, competition readiness, and scholarship awareness.</p></article></div></div></>}
 {page==='contact'&&<div className="contact-grid"><div><div className="contact-portrait"><Image src="/images/resanda-cutout.png" alt="Resanda" width={400} height={600}/><span className="speech-bubble">Let’s make<br/>something good. ✦</span></div><h3>Find me here.</h3><a className="contact-link" href={'mailto:'+profile.email}><span>Email</span><b>{profile.email} ↗</b></a><a className="contact-link" href={profile.linkedin} target="_blank" rel="noreferrer"><span>Connect</span><b>LinkedIn ↗</b></a><p className="location-note">{profile.location} · UTC+7</p></div><ContactComposer email={profile.email}/></div>}
 </section>{page!=='contact'&&<ChapterEnd/>}</main><Footer/></>
}
