import Image from 'next/image';
import Link from 'next/link';
import {Nav,Footer} from '@/components/site-shell';
import {ProjectCard,ChapterEnd} from '@/components/portfolio-ui';
import {getProjects,getExperiences,getProfile} from '@/lib/store';

export const dynamic='force-dynamic';
export default async function Home(){
 const [projects,experiences,profile]=await Promise.all([getProjects(),getExperiences(),getProfile()]);
 return <><Nav/><main id="main-content"><section className="hero section"><div className="hero-copy"><p className="eyebrow"><span className="live-dot"/> PRODUCT, DATA & A LITTLE CURIOSITY</p><p className="hero-intro">Hey, I’m Resanda. <span aria-hidden="true">✦</span></p><h1>Complex systems.<br/><i>Human stories.</i></h1><p className="lead">{profile.bio}</p><div className="actions"><Link className="primary" href="/projects">Explore my work ↗</Link><Link className="secondary" href="/about">Meet the person →</Link></div><div className="hero-footnote"><span>Based in {profile.location}</span><span>Scroll to explore ↓</span></div></div><div className="portrait-stage" data-tilt><span className="portrait-sun"/><span className="portrait-japanese" aria-hidden="true">好奇心</span><Image className="portrait" src="/images/resanda-cutout.png" alt="Resanda Dezca Asyam, wearing a white shirt" width={1024} height={1536} priority/><span className="portrait-star" aria-hidden="true">✦</span><div className="portrait-label"><span>THE PERSON BEHIND THE PRODUCT</span><b>Resanda Dezca Asyam</b></div><span className="portrait-sticker">Always<br/>building.</span></div></section>
 <div className="ticker" aria-label="Product thinking, systems, data, AI"><div aria-hidden="true">{[0,1].map(n=><span key={n}>PRODUCT THINKING ✦ SYSTEMS THAT WORK ✦ DATA TO DECISIONS ✦ AI WITH INTENTION ✦ </span>)}</div></div>
 <section className="section home-story"><div><p className="eyebrow">01 / THE ORIGIN STORY</p><h2>Curiosity is<br/>my <i>starting point.</i></h2><p>I work at the intersection of business, technology, and the people doing the work. From logistics operations to learning platforms, I turn complex problems into useful product decisions.</p><Link className="text-link" href="/about">Read my story ↗</Link></div><div className="story-notes"><article className="panel" data-tilt><span className="note-index">01</span><h3>Understand the real work.</h3><p>Listen to the people behind the process. Find the friction before designing the feature.</p></article><article className="panel" data-tilt><span className="note-index">02</span><h3>Make the next step clear.</h3><p>Bring research, data, and AI together to help teams act with confidence.</p></article></div></section>
 <section className="section impact"><p className="eyebrow">02 / A FEW THINGS THAT MOVED THE NEEDLE</p><div className="impact-grid">{[['30%','fewer logistics operational issues'],['~50%','less manual allocation effort'],['40–60%','faster business reporting'],['95%','critical UAT scenario coverage']].map(([value,label])=><article key={value}><strong>{value}</strong><span>{label}</span></article>)}</div><p className="impact-source">Selected outcomes reported in my CV, across Shopee, Unilever, and Bukalapak roles.</p></section>
 <section className="section"><div className="section-heading"><div><p className="eyebrow">03 / SELECTED STORIES</p><h2>Ideas out in<br/><i>the real world.</i></h2></div><Link className="text-link" href="/projects">Explore all projects ↗</Link></div><div className="project-grid">{projects.filter(p=>p.featured).slice(0,3).map((p,i)=><ProjectCard key={p.id} project={p} index={i}/>)}</div></section>
 <section className="section home-journey"><div><p className="eyebrow">04 / THE JOURNEY SO FAR</p><h2>Different teams.<br/><i>One curious mind.</i></h2><Link className="text-link" href="/experience">Full experience timeline ↗</Link></div><div>{experiences.slice(0,3).map(e=><article className="compact-role" key={e.id}><span>{e.company}</span><h3>{e.position}</h3><small>{e.period}</small></article>)}</div></section><ChapterEnd/></main><Footer/></>
}
