'use client';

import {Suspense,useEffect,useMemo,useRef,type RefObject} from 'react';
import {Canvas,useLoader,useThree} from '@react-three/fiber';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {gsap} from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import type {Group} from 'three';
import type {SceneVariant} from '../spatial-scene';

gsap.registerPlugin(ScrollTrigger);
const poses:Record<SceneVariant,{turn:number;train:number;lift:number;scale:number;tilt:number}>={home:{turn:-.2,train:-.55,lift:.45,scale:.94,tilt:0},about:{turn:-.48,train:-.2,lift:.12,scale:1.02,tilt:.04},experience:{turn:.12,train:-.85,lift:.05,scale:1,tilt:-.03},projects:{turn:-1.1,train:.1,lift:.2,scale:.98,tilt:.08},achievements:{turn:.7,train:.25,lift:.32,scale:.9,tilt:0},contact:{turn:1.3,train:-.1,lift:.08,scale:1.08,tilt:-.05},case:{turn:-.82,train:.35,lift:.17,scale:1.02,tilt:.05},admin:{turn:.35,train:-.35,lift:.14,scale:.9,tilt:0}};
function Marker({variant}:{variant:SceneVariant}){
 const color=({home:'#e7b44d',about:'#d96b55',experience:'#6484cb',projects:'#f0c75e',achievements:'#e79365',contact:'#d96b55',case:'#6b78b8',admin:'#b387d7'} as Record<SceneVariant,string>)[variant];
 if(variant==='experience')return <group position={[.3,1.35,.2]} rotation={[0,.4,0]}><mesh><torusGeometry args={[.56,.055,12,48]}/><meshStandardMaterial color={color} roughness={.6}/></mesh><mesh rotation={[Math.PI/2,0,0]}><torusGeometry args={[.34,.035,10,32]}/><meshStandardMaterial color="#fff5e4"/></mesh></group>;
 if(variant==='projects'||variant==='case')return <group position={[0,1.42,0]}><mesh rotation={[.5,.5,0]}><octahedronGeometry args={[.42,0]}/><meshStandardMaterial color={color} roughness={.55} metalness={.08}/></mesh><mesh rotation={[0,.5,.2]}><torusGeometry args={[.72,.025,8,48]}/><meshStandardMaterial color="#242641"/></mesh></group>;
 if(variant==='achievements')return <group position={[0,1.45,0]}><mesh><cylinderGeometry args={[.28,.4,.12,6]}/><meshStandardMaterial color={color}/></mesh><mesh position={[0,.37,0]}><octahedronGeometry args={[.3,0]}/><meshStandardMaterial color="#fff5e4"/></mesh></group>;
 if(variant==='contact')return <group position={[0,1.5,0]} rotation={[0,.55,.1]}><mesh><coneGeometry args={[.5,.82,4]}/><meshStandardMaterial color={color}/></mesh><mesh position={[0,.5,0]}><sphereGeometry args={[.07,16,16]}/><meshStandardMaterial color="#fff5e4" emissive="#fff5e4" emissiveIntensity={.6}/></mesh></group>;
 if(variant==='admin')return <group position={[0,1.42,0]}><mesh rotation={[0,.35,0]}><boxGeometry args={[.62,.42,.42]}/><meshStandardMaterial color={color}/></mesh><mesh position={[0,.5,0]}><sphereGeometry args={[.12,16,16]}/><meshStandardMaterial color="#fff5e4"/></mesh></group>;
 return <group position={[0,1.42,0]}><mesh rotation={[.35,.4,0]}><icosahedronGeometry args={[.35,0]}/><meshStandardMaterial color={color}/></mesh></group>;
}
function CoastalModel({host,story,variant,onReady}:{host:RefObject<HTMLDivElement|null>;story:boolean;variant:SceneVariant;onReady:()=>void}){
 const gltf=useLoader(GLTFLoader,'/models/coastal-studio.glb');const model=useMemo(()=>gltf.scene.clone(true),[gltf.scene]);const group=useRef<Group>(null);const {invalidate}=useThree();
 useEffect(()=>{if(!group.current||!host.current)return;const root=group.current,element=host.current,start=poses[variant],train=model.getObjectByName('Train'),houses=['Studio','Library','Workshop'].map(n=>model.getObjectByName(n)).filter(Boolean),baseTrain=train?.position.x||0,baseHouses=houses.map(h=>h?.position.y||0),pose={...start};const apply=()=>{root.rotation.set(pose.tilt,pose.turn,0);root.scale.setScalar(pose.scale);if(train)train.position.x=baseTrain+pose.train;houses.forEach((house,i)=>{if(house)house.position.y=baseHouses[i]+pose.lift*(.5+i*.18);});element.dataset.modelPose=[pose.turn,pose.train,pose.lift,pose.scale].map(v=>v.toFixed(3)).join(',');invalidate();};let timeline:gsap.core.Timeline|undefined;const setup=()=>{timeline?.kill();timeline?.scrollTrigger?.kill();const off=document.documentElement.dataset.motion==='off'||matchMedia('(prefers-reduced-motion: reduce)').matches;if(off){Object.assign(pose,{...start,train:0,lift:0,scale:1,tilt:0});apply();return;}const trigger=story?element.closest('.scroll-story'):element.closest('section');Object.assign(pose,start);apply();timeline=gsap.timeline({onUpdate:apply,scrollTrigger:{trigger,start:story?'top top':'top 12%',end:story?'bottom bottom':'bottom top',scrub:.7,invalidateOnRefresh:true}});timeline.to(pose,{turn:start.turn+.72,train:start.train+.72,lift:Math.max(0,start.lift-.18),scale:start.scale+.07,tilt:start.tilt*.2,duration:1,ease:'none'});timeline.to(pose,{turn:start.turn+1.36,train:start.train+1.36,lift:0,scale:start.scale+.12,tilt:-start.tilt,duration:1,ease:'none'});};setup();onReady();window.addEventListener('portfolio-motion-change',setup);return()=>{timeline?.scrollTrigger?.kill();timeline?.kill();window.removeEventListener('portfolio-motion-change',setup);};},[model,invalidate,host,story,variant,onReady]);
 return <group ref={group} position={[0,-.35,0]}><primitive object={model}/><Marker variant={variant}/></group>;
}
export default function CoastalCanvas({host,story,variant,onReady,onFailure}:{host:RefObject<HTMLDivElement|null>;story:boolean;variant:SceneVariant;onReady:()=>void;onFailure:()=>void}){return <Canvas className="model-canvas" frameloop="demand" dpr={[1,1.5]} camera={{position:[5.4,4.4,6.4],fov:36}} gl={{antialias:true,alpha:true,powerPreference:'low-power'}} onCreated={({gl})=>{gl.domElement.addEventListener('webglcontextlost',onFailure,{once:true});}}><ambientLight intensity={1.4}/><hemisphereLight args={['#fff5e4','#797a9d',1.3]}/><directionalLight position={[3,7,5]} intensity={2.6}/><Suspense fallback={null}><CoastalModel host={host} story={story} variant={variant} onReady={onReady}/></Suspense></Canvas>;}
